# Generated by Django 6.0.4 on 2026-04-14 23:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0002_rename_comment_comment12"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment12",
            new_name="Comment",
        ),
    ]
